### PR TITLE
Fix magnet effect

### LINKED ISSUE #61: Magnet effect wonky
Works inconsistently

### LINKED ISSUE #63: Resolve contrasting effect on entities
Enlarge + Shrink
Boost + Slow

### LINKED ISSUE #64: If paddle get enlarge effect at bottom of screen, it will grow more than screen size

### PR DESCRIPTION
**Pull request by ivantjh**
- Magnet effect is now controlled by paddle itself
- Contrasting effect should have their timers set properly

Fixes #61 
Fixes #63
Fixes #64

### CODE REVIEW

File: src/effects.cpp [hunk 1]
```diff
@@ -8,6 +8,39 @@ Effects::Effects() {}
 
 Effects::~Effects() {}
 
+bool Effects::effectExists(effectNS::EFFECT_TYPE effectType) {
+	for (effectDurationPair curr : currentEffects) {
+		if (curr.first == effectType)
+			return true;
+	}
```
Comment (chesterhow) [inline src/effects.cpp:15]: I thought unordered_map can access by key directly?

File: src/paddle.cpp [hunk 2]
```diff
@@ -163,14 +173,32 @@ void Paddle::runEffects() {
...
+	
+	int ballWidth = magnetBall->getWidth() * magnetBall->getScaleX();
+	int paddleWidth = spriteData.width * spriteData.scale.x;
+
+	// Ball will always stick to the front of paddle
+	if (magnetBall->getX() + ballWidth > spriteData.x && side == paddleNS::RIGHT) {
+		magnetBall->setX(spriteData.x - paddleWidth);
+	} 
+	else if (magnetBall->getX() - ballWidth < spriteData.x + paddleWidth && side == paddleNS::LEFT) {
+		magnetBall->setX(spriteData.x + paddleWidth);
```
Comment (chesterhow) [inline src/paddle.cpp]: If im not wrong what this does is, when the ball sticks to the top/bottom of the paddle, it gets shifted to the corner of the paddle?

File: src/pickupManager.cpp [hunk 3]
```diff
@@ -83,7 +83,43 @@ void PickupManager::massSpawnPickups(int side) {
...
+			VECTOR2(effectDataNS::TESTING_X_VELOCITY, 0));
+	}
+}
+
+void PickupManager::massSpawnPickups(std::vector<effectNS::EFFECT_TYPE> ev) {
+	Pickup* pickup;
+	
+	std::vector<effectNS::EffectData> effDataVec;
+
+	int size = static_cast<int>(ev.size());
```
Comment (chesterhow) [inline src/pickupManager.cpp]: Cannot just do `(int)(ev.size())` meh why must be hipster

File: src/pickupManager.cpp [hunk 4]
```diff
@@ -83,7 +83,43 @@ void PickupManager::massSpawnPickups(int side) {
...
+
+	for (size_t i = 0; i < 5; i++) {
```
Comment (chesterhow) [inline src/pickupManager.cpp]: looping through a integer probably shouldnt be using `size_t` here

**Review by chesterhow — CHANGES_REQUESTED** [review]

File: src/paddle.cpp (hunk 2 above)
Comment (ivantjh) [reply src/paddle.cpp]: Yeap

File: src/effects.cpp (hunk 1 above)
Comment (ivantjh) [reply src/effects.cpp:15]: Cannot access directly by key because using `enums` as key. `.find()` does not work here

File: src/paddle.cpp (hunk 2 above)
Comment (ivantjh) [reply src/paddle.cpp]: I think I will check for top

File: src/effects.cpp (hunk 1 above)
Comment (chesterhow) [reply src/effects.cpp:15]: Does something like `currentEffects[effectNS::BOOST]` not work?

Comment (ivantjh) [reply src/effects.cpp:15]: If a non-existence key is accessed,  the map will create a default constructed element for it. Since we are using the `currentEffects` for other forms of checking, we can't have default key value pairs in the map.

**Comment by ivantjh** [comment]
@chesterhow

File: src/effects.cpp (hunk 1 above)
Comment (chesterhow) [reply src/effects.cpp:15]: kk

**Review by chesterhow — APPROVED** [review]
